package junjange.core.local.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import junjange.core.local.dao.LotteryDao
import junjange.core.local.model.LotteryEntity

@Database(entities = [LotteryEntity::class], version = 1)
@ConstructedBy(LotteryDatabaseConstructor::class)
abstract class LotteryDatabase : RoomDatabase() {
    abstract fun lotteryDao(): LotteryDao
}

// The `actual` implementation is generated by Room's KSP processor for each platform.
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpectedDeclaration")
expect object LotteryDatabaseConstructor : RoomDatabaseConstructor<LotteryDatabase> {
    override fun initialize(): LotteryDatabase
}

internal const val LOTTERY_DATABASE_NAME = "lottery_database"
